# frontend nginx — configuración multi-máquina (deployment distribuido)
# Usado por docker-compose.m2.yml via volume mount
# Todos los backends referenciados por IP real de cada máquina

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA: todas las rutas van a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # → sps-lb en M2 (10.43.100.192:8080)
    location /sps/ {
        proxy_pass              http://10.43.100.192:8080/;
        proxy_set_header        Host              $host;
        proxy_set_header        X-Real-IP         $remote_addr;
        proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_connect_timeout   5s;
        proxy_read_timeout      30s;
    }

    # → saludpay-service en M3 (10.43.100.76:8082)
    location /spay/ {
        proxy_pass              http://10.43.100.76:8082/;
        proxy_set_header        Host              $host;
        proxy_set_header        X-Real-IP         $remote_addr;
        proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_connect_timeout   5s;
        proxy_read_timeout      30s;
    }

    # → shc-service en M4 (10.43.99.242:8083)
    location /shc/ {
        proxy_pass              http://10.43.99.242:8083/;
        proxy_set_header        Host              $host;
        proxy_connect_timeout   5s;
        proxy_read_timeout      30s;
    }

    # → sam-service en M4 (10.43.99.242:8084)
    location /sam/ {
        proxy_pass              http://10.43.99.242:8084/;
        proxy_set_header        Host              $host;
        proxy_connect_timeout   5s;
        proxy_read_timeout      30s;
    }
}
