# ============================================================
# M3 — 10.43.100.76  |  SPS instancia 2 + SaludPay
# Servicios: sps-service (inst 2), saludpay-service
# Prerequisito: M1 (RabbitMQ) ya debe estar corriendo
# ============================================================
services:

  sps-service:
    build: ./sps-service
    container_name: sps-service-m3
    restart: unless-stopped
    ports:
      - "8080:8080"   # Accedido por sps-lb en M2 como upstream
                      # H2 console: http://10.43.100.76:8080/h2-console
    environment:
      SPRING_RABBITMQ_HOST: 10.43.99.197      # M1
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: adminclientes
      SPRING_RABBITMQ_PASSWORD: adminclientes123
      SNS_BASE_URL: http://10.43.99.197:8081  # M1
      SPRING_MAIL_HOST: 10.43.99.197          # M1
      SPRING_MAIL_PORT: 1025

  saludpay-service:
    build: ./saludpay-service
    container_name: saludpay-service
    restart: unless-stopped
    ports:
      - "8082:8082"   # API SaludPay: http://10.43.100.76:8082
                      # Swagger UI: http://10.43.100.76:8082/swagger
    environment:
      RABBITMQ__HOST: 10.43.99.197      # M1
      RABBITMQ__PORT: "5672"
      RABBITMQ__USERNAME: adminclientes
      RABBITMQ__PASSWORD: adminclientes123
